apiVersion: v1
kind: Service
metadata:
  name: devpal-service
  namespace: devpal-review
spec:
  selector:
    app: devpal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
